In [5]:
import pandas as pd
import io

In [2]:
# Load the featureCounts output into a DataFrame
counts_file = "../results/featureCounts/cleaned_fcounts.txt" 
counts_df = pd.read_csv(counts_file, sep='\t')
counts_df.head()

,Geneid,SRR1552444_trimmed_aligned.bam,SRR1552445_trimmed_aligned.bam,SRR1552446_trimmed_aligned.bam,SRR1552447_trimmed_aligned.bam,SRR1552448_trimmed_aligned.bam,SRR1552449_trimmed_aligned.bam,SRR1552450_trimmed_aligned.bam,SRR1552451_trimmed_aligned.bam,SRR1552452_trimmed_aligned.bam,SRR1552453_trimmed_aligned.bam,SRR1552454_trimmed_aligned.bam,SRR1552455_trimmed_aligned.bam,Unnamed: 13
0,ENSMUSG00000104478,0,0,0,0,0,0,0,0,0,0,0,0,NaN
1,ENSMUSG00000104385,0,0,0,0,0,0,0,0,0,0,0,0,NaN
2,ENSMUSG00000101231,0,0,0,0,0,0,0,0,0,0,0,0,NaN
3,ENSMUSG00000102135,0,0,0,0,0,0,0,0,0,0,0,0,NaN
4,ENSMUSG00000103282,0,0,0,0,0,0,0,0,0,0,0,0,NaN

In [3]:
experiment_file = "../data/targets2.txt" 
experiment_file_df = pd.read_csv(experiment_file, sep='\t')
experiment_file_df.head()

,FileName,SampleName,CellType,Status,SRAFileName
0,MCL1.DG_BC2CTUACXX_ACTTGA_L002_R1,MCL1.DG,basal,virgin,SRR1552450.fastq.gz
1,MCL1.DH_BC2CTUACXX_CAGATC_L002_R1,MCL1.DH,basal,virgin,SRR1552451.fastq.gz
2,MCL1.DI_BC2CTUACXX_ACAGTG_L002_R1,MCL1.DI,basal,pregnant,SRR1552452.fastq.gz
3,MCL1.DJ_BC2CTUACXX_CGATGT_L002_R1,MCL1.DJ,basal,pregnant,SRR1552453.fastq.gz
4,MCL1.DK_BC2CTUACXX_TTAGGC_L002_R1,MCL1.DK,basal,lactate,SRR1552454.fastq.gz

In [13]:
# Create a dictionary to map file names to sample names
sample_mapping = dict(zip(experiment_file_df.iloc[:, 4].str.replace('.fastq.gz', '_trimmed_aligned.bam'), experiment_file_df.iloc[:, 1]))
sample_mapping
# Rename the columns in the counts DataFrame
counts_df.rename(columns=sample_mapping, inplace=True)
counts_df
#counts_df = counts_df.drop(columns=['Unnamed: 13'])
counts_df
# Save the updated DataFrame to a new file
counts_df.to_csv("../results/featureCounts/counts_matrix.csv", index=False)

,Geneid,MCL1.LA,MCL1.LB,MCL1.LC,MCL1.LD,MCL1.LE,MCL1.LF,MCL1.DG,MCL1.DH,MCL1.DI,MCL1.DJ,MCL1.DK,MCL1.DL
100,ENSMUSG00000065625,0,0,0,0,0,0,0,0,0,0,0,0
101,ENSMUSG00000103411,0,0,0,0,0,0,0,0,0,0,0,0
102,ENSMUSG00000061024,0,0,0,0,0,0,0,0,0,0,0,0
103,ENSMUSG00000102030,0,0,0,0,0,0,0,0,0,0,0,0
104,ENSMUSG00000025911,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ENSMUSG00000026254,0,0,0,0,0,0,0,0,0,0,0,0
996,ENSMUSG00000101468,0,0,0,0,0,0,0,0,0,0,0,0
997,ENSMUSG00000026405,0,0,0,0,0,0,0,0,0,0,0,0
998,ENSMUSG00000101227,0,0,0,0,0,0,0,0,0,0,0,0
999,ENSMUSG00000088318,0,0,0,0,0,0,0,0,0,0,0,0